server:
  port: 8088

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/msa1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true

  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: password
management:
  endpoints:
    web:
      exposure:
        include: "*"
