server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/thelovemsg/spring-basic
          search-paths: msa/msa2/git-local-repo/**
